title: mindpart
description: O komputerach i procesorach z dobrych czasów ;-)
logo: /assets/img/logo.png
lang: pl-PL
remote_theme: pages-themes/minimal@v0.2.0
show_downloads: false
plugins:
- jekyll-remote-theme